FROM docker.io/library/node:24-alpine AS builder

WORKDIR /app

RUN apk update && apk upgrade --no-cache

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"
ENV CI=true
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -

COPY package.json pnpm-lock.yaml* ./
COPY prisma ./prisma/

RUN pnpm install --no-frozen-lockfile --ignore-scripts

COPY . .

RUN npx prisma generate
RUN npx nest build
RUN CI=false pnpm prune --prod --ignore-scripts

FROM docker.io/library/node:24-alpine AS runner

WORKDIR /app

RUN apk update && apk upgrade --no-cache

ENV NODE_ENV=production
ENV PORT=3005

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

RUN mkdir -p /tmp/statements && chown -R node:node /tmp/statements

USER node

EXPOSE 3005

CMD ["node", "dist/main"]
