version: '3.8'

services:

  # ========================
  # INFRAESTRUCTURA
  # ========================

  mysql:
    image: mysql:8.0
    container_name: fintech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-12345}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./infra/mysql/init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME:-root}", "-p${DB_PASSWORD:-12345}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: fintech-kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s


  mailpit:
    image: axllent/mailpit:latest
    container_name: fintech-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:7-alpine
    container_name: fintech-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  # ========================
  # MICROSERVICIOS
  # ========================


  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: fintech-auth
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12345}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-mailpit}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-1025}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-noreply@fintechwallet.com}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-}
      SPRING_MAIL_AUTH: "${SPRING_MAIL_AUTH:-false}"
      SPRING_MAIL_STARTTLS: "${SPRING_MAIL_STARTTLS:-false}"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: auth-service
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: fintech-user
    ports:
      - "8082:8082"
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12345}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: user-service
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}

  transaction-service:
    build:
      context: ./backend/transaction-service
      dockerfile: Dockerfile
    container_name: fintech-transaction
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transactiondb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12345}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_APPLICATION_JSON: '{"spring.kafka.bootstrap-servers":"kafka:29092","user.service.url":"http://user-service:8082"}'
      GRPC_USER_SERVICE_ADDRESS: dns:///user-service:9090

      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: transaction-service
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: fintech-notification
    ports:
      - "8084:8084"
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      SPRING_APPLICATION_JSON: '{"spring.kafka.bootstrap-servers":"kafka:29092"}'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notificationdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12345}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-mailpit}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-1025}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-noreply@fintechwallet.com}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-}
      SPRING_MAIL_AUTH: "${SPRING_MAIL_AUTH:-false}"
      SPRING_MAIL_STARTTLS: "${SPRING_MAIL_STARTTLS:-false}"
      USER_SERVICE_URL: http://user-service:8082
      GRPC_USER_SERVICE_ADDRESS: dns:///user-service:9090

      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: notification-service
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}

  worker-service:
    build:
      context: ./backend/worker-service
      dockerfile: Dockerfile
    container_name: fintech-worker
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/workerdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12345}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_APPLICATION_JSON: '{"spring.kafka.bootstrap-servers":"kafka:29092"}'
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: worker-service
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: fintech-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - transaction-service
      - notification-service
      - worker-service
      - redis
    environment:
      SPRING_APPLICATION_JSON: '{"auth.service.url":"http://auth-service:8081","user.service.url":"http://user-service:8082","transaction.service.url":"http://transaction-service:8083","notification.service.url":"http://notification-service:8084","worker.service.url":"http://worker-service:8085"}'
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: ${OTEL_TRACES_SAMPLER:-always_on}
      OTEL_SERVICE_NAME: api-gateway
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER:-otlp}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER:-otlp}


  # ========================
  # FRONTEND
  # ========================

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fintech-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
      - otel-collector

  # ========================
  # SIGNOZ OBSERVABILITY
  # ========================

  clickhouse:
    image: clickhouse/clickhouse-server:25.12.5
    container_name: fintech-clickhouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./infra/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./infra/clickhouse/users.xml:/etc/clickhouse-server/users.d/experimental.xml:ro
    healthcheck:

      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  signoz-telemetrystore-migrator:
    image: signoz/signoz-otel-collector:v0.144.6
    container_name: fintech-signoz-telemetrystore-migrator
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate bootstrap --config /etc/otel-collector-config.yaml && \
        /signoz-otel-collector migrate sync up --config /etc/otel-collector-config.yaml && \
        /signoz-otel-collector migrate async up --config /etc/otel-collector-config.yaml
    volumes:
      - ./infra/otel/otel-migration-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
    depends_on:
      clickhouse:
        condition: service_healthy

  signoz:
    image: signoz/signoz:v0.132.2
    container_name: fintech-signoz
    ports:
      - "3301:8080"
    environment:
      - STORAGE=clickhouse
      - ClickHouseUrl=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
    volumes:
      - signoz-sqlite:/var/lib/signoz
    depends_on:
      clickhouse:
        condition: service_healthy
      signoz-telemetrystore-migrator:
        condition: service_completed_successfully

  otel-collector:
    image: signoz/signoz-otel-collector:v0.144.6
    container_name: fintech-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    user: "0"
    volumes:
      - ./infra/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      clickhouse:
        condition: service_healthy
      signoz-telemetrystore-migrator:
        condition: service_completed_successfully

  signoz-mcp-server:
    image: signoz/signoz-mcp-server:latest
    container_name: fintech-signoz-mcp-server
    ports:
      - "8000:8000"
    environment:
      - TRANSPORT_MODE=http
      - MCP_SERVER_PORT=8000
      - SIGNOZ_URL=http://signoz:8080
      - SIGNOZ_API_KEY=${SIGNOZ_API_KEY}
    depends_on:
      - signoz

volumes:
  mysql-data:
  clickhouse-data:
  signoz-sqlite:
  redis-data:

