# Stage 1: Build
FROM docker.io/library/node:24-alpine AS builder

WORKDIR /app

RUN apk update && apk upgrade --no-cache

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"
ENV CI=true
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
COPY prisma ./prisma/

RUN pnpm install --no-frozen-lockfile --ignore-scripts
COPY . .

RUN npx prisma generate
RUN pnpm run build
RUN CI=false pnpm prune --prod --ignore-scripts

# Stage 2: Production
FROM docker.io/library/node:24-alpine AS runner

WORKDIR /app

RUN apk update && apk upgrade --no-cache

ENV NODE_ENV=production
ENV PORT=3004

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
COPY prisma ./prisma/

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3004

CMD ["node", "dist/main"]
