apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.global.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.global.dbPassword | quote }}
  POSTGRES_USER: {{ .Values.global.dbUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.dbPassword | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
