apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS transactiondb;
    CREATE DATABASE IF NOT EXISTS notificationdb;
    CREATE DATABASE IF NOT EXISTS workerdb;

    CREATE USER IF NOT EXISTS '{{ .Values.global.dbUsername }}'@'%' IDENTIFIED BY '{{ .Values.global.dbPassword }}';
    GRANT ALL PRIVILEGES ON *.* TO '{{ .Values.global.dbUsername }}'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.global.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.global.dbPassword | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
