apiVersion: v1
kind: Namespace
metadata:
  name: fintech
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: fintech
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS transactiondb;
    CREATE DATABASE IF NOT EXISTS notificationdb;
    CREATE DATABASE IF NOT EXISTS workerdb;

    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '12345';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: fintech
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "12345"
  JWT_SECRET: "dGhpc2lzYXNlY3JldGtleWZvcmp3dHRva2VudmFsaWRhdGlvbmZpbnRlYch3YWxsZXQ="
