allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  prisma: true
  protobufjs: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - protobufjs
