spring.application.name=api-gateway
server.port=8080

# JWT
jwt.secret=ZmludGVjaC1zZWNyZXQta2V5LXN1cGVyLXNlY3VyZS0yNTYtYml0cy1sb25nLWtleQ==

auth.service.url=http://localhost:8081
user.service.url=http://localhost:8082
transaction.service.url=http://localhost:8083
notification.service.url=http://localhost:8084

# Actuator config
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
