spring.application.name=api-gateway
server.port=8080

# JWT
jwt.secret=ZmludGVjaC1zZWNyZXQta2V5LXN1cGVyLXNlY3VyZS0yNTYtYml0cy1sb25nLWtleQ==

auth.service.url=http://localhost:8081
user.service.url=http://localhost:8082
transaction.service.url=http://localhost:8083
notification.service.url=http://localhost:8084

# Actuator config
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Springdoc properties
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service API
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=User Service API
springdoc.swagger-ui.urls[1].url=/users/v3/api-docs
springdoc.swagger-ui.urls[2].name=Transaction Service API
springdoc.swagger-ui.urls[2].url=/transactions/v3/api-docs
springdoc.swagger-ui.urls[3].name=Notification Service API
springdoc.swagger-ui.urls[3].url=/notifications/v3/api-docs
